### ISSUE TITLE
musicdb artwork module requires absolute artwork path

### ISSUE THREAD

**Issue by rstemmer** [rstemmer/musicdb#34]
Adding artwork for an album fails, if the artwork path is not absolute.
In the following example, both calls should work, but only the second one succeeds.

```bash
cd ~
musicdb artwork -u --artwork tmp.jpg --album /data/music/Artist/2020\ -\ Album
musicdb artwork -u --artwork /home/user/tmp.jpg --album /data/music/Artist/2020\ -\ Album
```

The error appers in `mdbapi/artwork.py:321:   if artworkpath and not self.fs.IsFile(artworkpath):`
The root for `fs` is `/` and therefore relative paths are interpreted as being relative to the systems root directory.
This is correct, because the the command line modules should make all user defined paths absolute before calling MusicDB internal functions.
So `mod/artwork.py` fails at this point.

**Comment by siddhantchimankar** [comment]
Hello, beginner here. Can I work on this?

**Comment by rstemmer** [comment]
Yes, of course

**Comment by rstemmer** [comment]
I fixed the bug → issue closed
