### ISSUE TITLE
Fix install recommendation for Ubuntu

### ISSUE THREAD

**Issue by gerritb** [rstemmer/musicdb#84]
# Issue
## Expected Behavior

to be in sudoers after usermod recommendation

## Actual Behavior

usermod adds user to musicdb group but removes user from all other groups

# Steps to reproduce

sudo usermod -G musicdb $username (please don't try)

# Workarounds

Change docs to 
sudo usermod -aG musicdb $username
add -a to usermod command
https://linux.die.net/man/8/usermod

# Detailed Information

In the following subsections you can paste all warning, error messages and traces you can find.
If you are not sure if an information is related to the issue, just paste it anyway.
When debugging, you cannot have too much information.

Warnings, Error Messages

```
Please post traces as code
```

## Server Side Information

What does MusicDB's WebSocket Server say

## Client Side Information

Are there any information the web browser provides.
Right click somewhere in the WebUI and select *Insepct*.
Open the *Console* tab and try to reproduce the Issue.

Please append the **debug.ansi** file from the MusicDB data directory.

**Comment by rstemmer** [comment]
Thank you for reporting this issue. I'm very sorry for any inconveniences and harm that this missing flag caused.

I fixed the lines by adding the missing `-a` and improved them by using the long parameter names.
```bash
sudo usermod --append --groups musicdb $username
```
